//! ついたて将棋bot のライブラリ部分。
//!
//! main.rs（本番bot）と bin/arena.rs（戦略同士のローカル対戦）が共有する。

pub mod board;
pub mod bridge;
pub mod check;
pub mod client;
pub mod deduce;
pub mod estimator;
pub mod frozen;
pub mod kifu;
pub mod likelihood;
pub mod model;
pub mod observation;
pub mod opening;
pub mod opp_move_features;
pub mod opp_move_nn;
pub mod protocol;
pub mod record;
pub mod selfplay;
pub mod shogi;
pub mod strategy;
pub mod value_features;
pub mod value_nn;
pub mod webhook_csa;
pub mod webhook_hmac;
pub mod webhook_protocol;
pub mod webhook_session;
